README.md
src/kani_lib/kani_collector.rs
src/printer.rs

This PR makes a series of changes:
1.  the biggest one --- a new top-level field `functions` is added that points to a map from interned `Ty`s (numbers) to link-time function symbol names (strings)
2.  the structure of `MonoItemFn`s changed as follows:
-   several debug fields were removed and put in the `ItemDetails` struct instead
-   the `body` and `promoted` array were unified into a single array field
3.  the `MirBody` struct was removed and the `BodyDetails` struct was moved to a new array field in `ItemDetails`
4.  some new env vars were added to control how the link map is built and how debug information is emitted
The construction of the linking map is done in two phases:
-   (optionally) each `MonoItem::Fn(Instance)` has its `Instance`s underlying function type mapped to the …

Map function types to names and update output format

---

src/printer.rs

This update fixes three issues in three commits:
1.  it fixes an infinite loop condition when doing link map construction
2.  it fixes an issue where a crash would occur when we tried to lookup the name of `GlobalAsm` mono items;
3.  it fixes a crash when building the link map for the standard library using `cargo build -Zbuild-std` where calling `inst.ty()` failed in a case when the underlying function type was already known

Fix bugs in item collection

---

run.sh

Removes erroneous ":" from `:D_LIBRARY_PATH`

HOTFIX: use `SEP` variable for `LD_LIBRARY_PATH` modification in run script

---

src/printer.rs

Now we always check for collisions in `update_link_map` so long as debug logging is enabled

Weakened guard for logging in `update_link_map`

---

Cargo.lock
src/printer.rs

Creating the layout for a `Binder<DUMMY>` is creating panics, see https://github.com/runtimeverification/smir_pretty/issues/27 for details. This PR does not solve the problem but side steps it. There may be other times that this will be needed unless we find a fix to get the `Layout` without triggering the error.

Temporary fix for layout of panic strings

---

Cargo.lock
Cargo.toml
README.md
src/lib.rs
src/main.rs
src/mk_graph.rs
src/printer.rs

In this first version we don't draw the statements of blocks, just the block structure and caller/callee relations between blocks/items.
In terms of interface, the `main` program now has options `--json` and `--dot` which have to come first, and we default to `--json` if they are absent.
Output example: (main calls `foo(0)` calls `bar(0)`)
The HS version had more color but was otherwise the same:

Option to generate a dot file representing the smir-json

---

Makefile
src/mk_graph.rs

* field projections are rendered as suffix `.N` where `N` is the field index
* array indexing (constant or with a local) is rendered as `[IDX]`, where `IDX` is either a local written with `_` prefix or a plain integer
* dereferencing is rendered as a `*` suffix (NB _not_ prefix, for practicality)
* type casts and subtyping are rendered by appending `as _TYPE_`

Render projections in the SMIR graph of basic blocks

---

src/printer.rs

Currently `stable-mir-json` will not build complex programs. This PR makes some changes so that [p-token](https://github.com/febo/p-token) will build as long as [this feature flag in pinocchio](https://github.com/anza-xyz/pinocchio/blob/1a10e2277303d843e8f2922d4efab87f41d82aff/sdk/log/crate/Cargo.toml#L20) is removed (this is unneeded to build p-token so it is no problem to remove it)
- Added `Adt` and `Ref` type handling for the `RigidTy`s in `get_prov_type` as seen in #32 
- Side steps the DUMMY_BINDER escaping bound vars in formatting arguments as seen in #27

Fixing some errors so p-token builds

---

src/bin/cargo_stable_mir_json.rs
src/mk_graph.rs

Tweaks to graph rendering
* Reference creation and dereferencing are now rendered differently:
- dereference: `& ...` or `&mut ...`, 
* operand copy and operand move are now indicated by `cp(...)` and `mv(...)`
Tweaks to installed run script:
* environment variable `STABLE_MIR_OPTS` can be set to pass `--dot` or `--json` (or any number of other options) directly to the compiler invocation
* the script now uses its location as a path prefix instead of fixing it to the installation directory, i.e., the installation can be moved to a different directory without breaking

Small tweaks to graph and installed script

---

src/mk_graph.rs
src/printer.rs
tests/integration/programs/assert_eq.smir.json.expected
tests/integration/programs/binop.smir.json.expected
tests/integration/programs/char-trivial.smir.json.expected
tests/integration/programs/closure-args.smir.json.expected
tests/integration/programs/closure-no-args.smir.json.expected
tests/integration/programs/const-arithm-simple.smir.json.expected
tests/integration/programs/div.smir.json.expected
tests/integration/programs/double-ref-deref.smir.json.expected
tests/integration/programs/enum.smir.json.expected
tests/integration/programs/fibonacci.smir.json.expected
tests/integration/programs/float.smir.json.expected
tests/integration/programs/modulo.smir.json.expected
tests/integration/programs/mutual_recursion.smir.json.expected
tests/integration/programs/option-construction.smir.json.expected
tests/integration/programs/primitive-type-bounds.smir.json.expected
tests/integration/programs/recursion-simple-match.smir.json.expected
tests/integration/programs/recursion-simple.smir.json.expected
tests/integration/programs/ref-deref.smir.json.expected
tests/integration/programs/shl_min.smir.json.expected
tests/integration/programs/slice.smir.json.expected
tests/integration/programs/strange-ref-deref.smir.json.expected
tests/integration/programs/struct.smir.json.expected
tests/integration/programs/sum-to-n.smir.json.expected
tests/integration/programs/tuple-eq.smir.json.expected
tests/integration/programs/tuples-simple.smir.json.expected

Stable MIR `Instance` `Body` has already allocated promoted, [see this conversation on zulip]([#project-stable-mir > Getting fully monomorphised &#96;MonoItem&#96;s @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/320896-project-stable-mir/topic/Getting.20fully.20monomorphised.20.60MonoItem.60s/near/507085029))

Removed the multiple `Body`s for `Instance`

---

src/mk_graph.rs
src/printer.rs
tests/integration/normalise-filter.jq
tests/integration/programs/assert_eq.smir.json.expected
tests/integration/programs/binop.smir.json.expected
tests/integration/programs/char-trivial.smir.json.expected
tests/integration/programs/closure-args.smir.json.expected
tests/integration/programs/closure-no-args.smir.json.expected
tests/integration/programs/const-arithm-simple.smir.json.expected
tests/integration/programs/div.smir.json.expected
tests/integration/programs/double-ref-deref.smir.json.expected
tests/integration/programs/enum.smir.json.expected
tests/integration/programs/fibonacci.smir.json.expected
tests/integration/programs/float.smir.json.expected
tests/integration/programs/modulo.smir.json.expected
tests/integration/programs/mutual_recursion.smir.json.expected
tests/integration/programs/option-construction.smir.json.expected
tests/integration/programs/primitive-type-bounds.smir.json.expected
tests/integration/programs/recursion-simple-match.smir.json.expected
tests/integration/programs/recursion-simple.smir.json.expected
tests/integration/programs/ref-deref.smir.json.expected
tests/integration/programs/shl_min.smir.json.expected
tests/integration/programs/slice.smir.json.expected
tests/integration/programs/strange-ref-deref.smir.json.expected
tests/integration/programs/struct.smir.json.expected
tests/integration/programs/sum-to-n.smir.json.expected
tests/integration/programs/tuple-eq.smir.json.expected
tests/integration/programs/tuples-simple.smir.json.expected

As it turns out, the `SwitchInt` terminator uses `discriminants` (computed using `RValue::Discriminant` ) but when an enum value is created we only have the `VariantIdx` (`0..n` in source order, including uninhabited variants).
This PR extracts a mapping of `VariantIdx` to discriminants (bytes stored as `u128`) as type metadata for each `enum`  that can be used in the semantics to implement the `RValue::Discriminant`.

Extract discriminant information

---

panic_example.rs
panic_example.smir.json
src/printer.rs
tests/integration/normalise-filter.jq

These `adt_def`  of `struct` and `enum` metadata are required for a reverse mapping `adt_def -> Ty` in the semantics. 
The `AggregateKind` only carries the `adt_def` but we have to look up the discriminant information (and potentially other metadata later) from a `Ty` key.
Note that the `adt_def` is unstable, it changes with every compiler run, so we delete the field in the golden tests.

Add adt_def to struct and enum metadata

---

src/mk_graph.rs
src/printer.rs
tests/integration/programs/assert_eq.smir.json.expected
tests/integration/programs/binop.smir.json.expected
tests/integration/programs/char-trivial.smir.json.expected
tests/integration/programs/closure-args.smir.json.expected
tests/integration/programs/closure-no-args.smir.json.expected
tests/integration/programs/const-arithm-simple.smir.json.expected
tests/integration/programs/div.smir.json.expected
tests/integration/programs/double-ref-deref.smir.json.expected
tests/integration/programs/enum.smir.json.expected
tests/integration/programs/fibonacci.smir.json.expected
tests/integration/programs/float.smir.json.expected
tests/integration/programs/modulo.smir.json.expected
tests/integration/programs/mutual_recursion.smir.json.expected
tests/integration/programs/option-construction.smir.json.expected
tests/integration/programs/primitive-type-bounds.smir.json.expected
tests/integration/programs/recursion-simple-match.smir.json.expected
tests/integration/programs/recursion-simple.smir.json.expected
tests/integration/programs/ref-deref.smir.json.expected
tests/integration/programs/shl_min.smir.json.expected
tests/integration/programs/slice.smir.json.expected
tests/integration/programs/strange-ref-deref.smir.json.expected
tests/integration/programs/struct.smir.json.expected
tests/integration/programs/sum-to-n.smir.json.expected
tests/integration/programs/tuple-eq.smir.json.expected
tests/integration/programs/tuples-simple.smir.json.expected

- I removed rendering an empty node for the graph if the `MonoItem::Fn` has no `Body`, I have not had time to dig much more into it but the graph should have the empty node replaced. 
- Accessing the name for `Adt` is not done with the `Stable MIR` API, updating to doing this means the names are slightly different (as can be seen in the diff) but I don't think the information using the internal method has anything needed

Updates: Graph and `Adt` names

---

.github/workflows/test.yml
src/printer.rs
tests/integration/normalise-filter.jq
tests/integration/programs/assert_eq.smir.json.expected
tests/integration/programs/binop.smir.json.expected
tests/integration/programs/char-trivial.smir.json.expected
tests/integration/programs/closure-args.smir.json.expected
tests/integration/programs/closure-no-args.smir.json.expected
tests/integration/programs/const-arithm-simple.smir.json.expected
tests/integration/programs/div.smir.json.expected
tests/integration/programs/double-ref-deref.smir.json.expected
tests/integration/programs/enum.smir.json.expected
tests/integration/programs/fibonacci.smir.json.expected
tests/integration/programs/float.smir.json.expected
tests/integration/programs/modulo.smir.json.expected
tests/integration/programs/mutual_recursion.smir.json.expected
tests/integration/programs/option-construction.smir.json.expected
tests/integration/programs/primitive-type-bounds.smir.json.expected
tests/integration/programs/recursion-simple-match.smir.json.expected
tests/integration/programs/recursion-simple.smir.json.expected
tests/integration/programs/ref-deref.smir.json.expected
tests/integration/programs/shl_min.smir.json.expected
tests/integration/programs/slice.smir.json.expected
tests/integration/programs/strange-ref-deref.smir.json.expected
tests/integration/programs/struct.smir.json.expected
tests/integration/programs/sum-to-n.smir.json.expected
tests/integration/programs/tuple-eq.smir.json.expected
tests/integration/programs/tuples-simple.smir.json.expected
tests/ui/run_ui_tests.sh

Emit metadata for all types that matter, in particular reference types and array types.
Function types are only referred to as strings (elided in the golden tests), some other types are still not considered but they don't seem relevant to our purpose.
Also included:
* add type of `TyConst` in `RigidTy::Array` case to collected types in `collect_ty`
* optionally keep json files after running `test-ui`
| RigidTy                                          | Metadata      | Information     |           |
|--------------------------------------------------|---------------|-----------------|-----------|
| Bool                                             | PrimitiveType | RigidTy         | existed   |
| Char                                             | PrimitiveType | RigidTy         | existed   | …

More type metadata

---

.github/workflows/master.yml
.github/workflows/test.yml

This coupled with https://github.com/runtimeverification/devops/pull/233, should automatically open update PRs into KMIR when there are updates to this repo. These PRs will be opened by the RV Jenkins GitHub user, and just need to be approved to be merged.

Update dependents automatically on master pushes

---

.github/workflows/master.yml

Blocked on: https://github.com/runtimeverification/devops/pull/234
Blocked on: https://github.com/runtimeverification/mir-semantics/pull/561
This uses `git rev-parse` instead of relying on github action variables to get the version to push, as the prior attempt didn't end up including the label.

Use git rev-parse to get master version

---

.github/workflows/master.yml
Makefile

The make target `test-ui` takes a verbosity flag to print the output. This flag is provided as env var `VERBOSE`, but this was not being read properly from the environment and was always set to `0`

Fixed `VERBOSE` env var reading in `Makefile`

---

src/printer.rs

Added [MachineInfo](https://github.com/rust-lang/rust/blob/a2545fd6fc66b4323f555223a860c451885d1d2b/compiler/stable_mir/src/target.rs#L7-L12) to the JSON. This should give us the ability to use `usize` properly

`MachineInfo` in JSON

---

src/printer.rs
tests/integration/normalise-filter.jq
tests/integration/programs/assert_eq.smir.json.expected
tests/integration/programs/binop.smir.json.expected
tests/integration/programs/char-trivial.smir.json.expected
tests/integration/programs/closure-args.smir.json.expected
tests/integration/programs/closure-no-args.smir.json.expected
tests/integration/programs/const-arithm-simple.smir.json.expected
tests/integration/programs/div.smir.json.expected
tests/integration/programs/double-ref-deref.smir.json.expected
tests/integration/programs/enum.smir.json.expected
tests/integration/programs/fibonacci.smir.json.expected
tests/integration/programs/float.smir.json.expected
tests/integration/programs/modulo.smir.json.expected
tests/integration/programs/mutual_recursion.smir.json.expected
tests/integration/programs/option-construction.smir.json.expected
tests/integration/programs/primitive-type-bounds.smir.json.expected
tests/integration/programs/recursion-simple-match.smir.json.expected
tests/integration/programs/recursion-simple.smir.json.expected
tests/integration/programs/ref-deref.smir.json.expected
tests/integration/programs/shl_min.smir.json.expected
tests/integration/programs/slice.smir.json.expected
tests/integration/programs/strange-ref-deref.smir.json.expected
tests/integration/programs/struct.smir.json.expected
tests/integration/programs/sum-to-n.smir.json.expected
tests/integration/programs/tuple-eq.smir.json.expected
tests/integration/programs/tuples-simple.smir.json.expected

This adds the field types of the single variant of a `struct` `RigidTy::Adt` to the type metadata, similar to the `types` field of `TupleType`
Closes #81

Add a list of field types to struct type metadata

---

src/printer.rs
tests/integration/programs/assert_eq.smir.json.expected

The `Ty`s found in field information can contain `AliasTy` as well as `ParamTy`, and potentially have unevaluated constants.
Also now panicking if an unevaluated constant is found in array type metadata.
In the discussion, it was pointed out that the variant fields can be obtained using `stable_mir` crate (interface) methods only, so I refactored the code to not use internals where possible.
Related Zulip discussion:[#project-stable-mir > Visiting ADT field types, problem with unevaluated constants](https://rust-lang.zulipchat.com/#narrow/channel/320896-project-stable-mir/topic/Visiting.20ADT.20field.20types.2C.20problem.20with.20unevaluated.20constants)

HOTFIX normalise field types before emitting them

---

src/bin/cargo_stable_mir_json.rs

- Add operating system detection in record_ld_library_path function
- Use DYLD_LIBRARY_PATH on macOS instead of LD_LIBRARY_PATH
- Include Rust toolchain path in default library path for macOS
- Add DYLD_LIBRARY_PATH export in generated shell scripts for macOS
- Maintain backward compatibility with Linux and other systems

Add macOS support to stable-mir-json
